name: Build APK

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build project with Gradle
        run: chmod +x ./gradlew && ./gradlew build

      - name: Upload as artifact
        uses: actions/upload-artifact@v2
        with:
          name: mod
          path: |
           mod/build/libs/Light-Switch-App.jar
